# Generated by Django 4.1.1 on 2022-12-14 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appMaverick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
